# Generated by Django 5.2.16 on 2026-07-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
            ],
            options={
                'verbose_name': 'نوع معامله',
                'verbose_name_plural': 'انواع معامله',
                'db_table': 'basics_deal_type',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'انواع ملک',
                'db_table': 'basics_property_type',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('data_type', models.CharField(choices=[('text', 'متن'), ('integer', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('boolean', 'بله / خیر'), ('date', 'تاریخ'), ('select', 'انتخاب یکی'), ('multiselect', 'انتخاب چندتایی')], max_length=20, verbose_name='نوع داده')),
                ('input_type', models.CharField(choices=[('default', 'پیش\u200cفرض'), ('price', 'مبلغ')], default='default', help_text='«مبلغ» باعث نمایش جداکننده هزارگان در فرم می\u200cشود.', max_length=20, verbose_name='نوع ورودی')),
                ('filter_type', models.CharField(choices=[('none', 'بدون فیلتر'), ('exact', 'تطابق دقیق'), ('range', 'بازه\u200cای'), ('range_fast', 'بازه\u200cای (سریع)'), ('exists', 'وجود دارد')], default='none', max_length=20, verbose_name='نوع فیلتر')),
                ('entity', models.CharField(choices=[('property', 'ملک'), ('listing', 'آگهی')], db_index=True, default='property', max_length=20, verbose_name='مربوط به')),
                ('unit', models.CharField(blank=True, help_text='مثلاً متر مربع، تومان، عدد.', max_length=50, verbose_name='واحد')),
                ('is_facility', models.BooleanField(default=False, help_text='ویژگی\u200cهای بله/خیر مانند آسانسور و پارکینگ که به صورت گروهی نمایش داده می\u200cشوند.', verbose_name='امکانات رفاهی')),
                ('is_core', models.BooleanField(default=False, help_text='ویژگی\u200cهای ثابت در ستون اختصاصی و ایندکس\u200cشده ذخیره می\u200cشوند (مانند متراژ و قیمت) و در جستجو سریع\u200cتر هستند. بقیه ویژگی\u200cها به صورت پویا ذخیره می\u200cشوند.', verbose_name='فیلد ثابت')),
                ('core_field', models.CharField(blank=True, help_text='نام فیلد مدل که این ویژگی به آن نگاشت می\u200cشود (فقط برای فیلدهای ثابت).', max_length=50, verbose_name='نام ستون ثابت')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'db_table': 'basics_attribute',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity', 'sort_order'], name='basics_attr_entity_b32770_idx'), models.Index(condition=models.Q(('is_facility', True)), fields=['is_facility'], name='idx_attribute_facility')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_attribute_name_alive')],
            },
        ),
        migrations.CreateModel(
            name='DealTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='basics.dealtype', verbose_name='نوع معامله')),
            ],
            options={
                'verbose_name': 'ویژگی نوع معامله',
                'verbose_name_plural': 'ویژگی\u200cهای نوع معامله',
                'db_table': 'basics_deal_type_attribute',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='dealtype',
            name='attributes',
            field=models.ManyToManyField(related_name='deal_types', through='basics.DealTypeAttribute', to='basics.attribute', verbose_name='ویژگی\u200cها'),
        ),
        migrations.CreateModel(
            name='DealTypeSearchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_attribute_links', to='basics.dealtype', verbose_name='نوع معامله')),
            ],
            options={
                'verbose_name': 'فیلتر جستجوی نوع معامله',
                'verbose_name_plural': 'فیلترهای جستجوی نوع معامله',
                'db_table': 'basics_deal_type_search_attribute',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='basics.propertytype', verbose_name='نوع ملک')),
            ],
            options={
                'verbose_name': 'ویژگی نوع ملک',
                'verbose_name_plural': 'ویژگی\u200cهای نوع ملک',
                'db_table': 'basics_property_type_attribute',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='propertytype',
            name='attributes',
            field=models.ManyToManyField(related_name='property_types', through='basics.PropertyTypeAttribute', to='basics.attribute', verbose_name='ویژگی\u200cها'),
        ),
        migrations.CreateModel(
            name='PropertyTypeSearchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_attribute_links', to='basics.propertytype', verbose_name='نوع ملک')),
            ],
            options={
                'verbose_name': 'فیلتر جستجوی نوع ملک',
                'verbose_name_plural': 'فیلترهای جستجوی نوع ملک',
                'db_table': 'basics_property_type_search_attribute',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
            ],
            options={
                'verbose_name': 'کاربری ملک',
                'verbose_name_plural': 'کاربری\u200cهای ملک',
                'db_table': 'basics_property_usage',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_property_usage_name_alive')],
            },
        ),
        migrations.AddField(
            model_name='propertytype',
            name='property_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_types', to='basics.propertyusage', verbose_name='کاربری ملک'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('value', models.CharField(help_text='کلید ذخیره\u200cشده در پایگاه داده (انگلیسی و ثابت).', max_length=100, verbose_name='مقدار')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='basics.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'گزینه ویژگی',
                'verbose_name_plural': 'گزینه\u200cهای ویژگی',
                'db_table': 'basics_attribute_option',
                'ordering': ['sort_order', 'display_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('attribute', 'value'), name='uq_attribute_option_value_alive')],
            },
        ),
        migrations.AddIndex(
            model_name='dealtypeattribute',
            index=models.Index(fields=['deal_type', 'is_active', 'sort_order'], name='basics_deal_deal_ty_7842ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealtypeattribute',
            constraint=models.UniqueConstraint(fields=('deal_type', 'attribute'), name='uq_deal_type_attribute'),
        ),
        migrations.AddConstraint(
            model_name='dealtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_deal_type_name_alive'),
        ),
        migrations.AddIndex(
            model_name='dealtypesearchattribute',
            index=models.Index(fields=['deal_type', 'is_active', 'sort_order'], name='basics_deal_deal_ty_b40cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealtypesearchattribute',
            constraint=models.UniqueConstraint(fields=('deal_type', 'attribute'), name='uq_deal_type_search_attribute'),
        ),
        migrations.AddIndex(
            model_name='propertytypeattribute',
            index=models.Index(fields=['property_type', 'is_active', 'sort_order'], name='basics_prop_propert_31a1a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytypeattribute',
            constraint=models.UniqueConstraint(fields=('property_type', 'attribute'), name='uq_property_type_attribute'),
        ),
        migrations.AddIndex(
            model_name='propertytypesearchattribute',
            index=models.Index(fields=['property_type', 'is_active', 'sort_order'], name='basics_prop_propert_e68691_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytypesearchattribute',
            constraint=models.UniqueConstraint(fields=('property_type', 'attribute'), name='uq_property_type_search_attribute'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['property_usage', 'sort_order'], name='basics_prop_propert_a83315_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_property_type_name_alive'),
        ),
    ]
