# Generated by Django 5.2.16 on 2026-07-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'db_table': 'basics_province',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_province_name_alive')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='basics.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'db_table': 'basics_city',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(db_index=True, help_text='شناسه انگلیسی و ثابت (مانند apartment). پس از ایجاد تغییر نکند.', max_length=100, verbose_name='کلید سیستمی')),
                ('display_name', models.CharField(max_length=255, verbose_name='نام نمایشی')),
                ('sort_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ترتیب نمایش')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='basics.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله\u200cها',
                'db_table': 'basics_district',
                'ordering': ['sort_order', 'display_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['city', 'sort_order'], name='basics_dist_city_id_7bd828_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('city', 'name'), name='uq_district_name_per_city_alive')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'sort_order'], name='basics_city_provinc_74e5ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('province', 'name'), name='uq_city_name_per_province_alive'),
        ),
    ]
