# Generated by Django 5.2.16 on 2026-08-23 08:43

import apps.tickets.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("followups", "0003_alter_followup_options"),
        ("listings", "0006_alter_listing_status"),
        ("properties", "0013_backfill_owner_info"),
        ("tasks", "0003_task_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="شماره تیکت",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان تیکت"
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("QUESTION", "پرسش"),
                            ("REQUEST", "درخواست"),
                            ("ALERT", "هشدار"),
                            ("ISSUE", "گزارش مشکل"),
                            ("COMPLAINT", "شکایت"),
                            ("ANNOUNCEMENT", "اطلاع\u200cرسانی"),
                            ("OTHER", "سایر"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                        verbose_name="نوع تیکت",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "عادی"),
                            ("IMPORTANT", "مهم"),
                            ("URGENT", "فوری"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "باز"),
                            ("WAITING_REPLY", "در انتظار پاسخ"),
                            ("ANSWERED", "پاسخ\u200cداده\u200cشده"),
                            ("CLOSED", "بسته"),
                        ],
                        db_index=True,
                        default="WAITING_REPLY",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("PROPERTY", "املاک موجود"),
                            ("LISTING", "آگهی\u200cهای موجود"),
                            ("FOLLOWUP", "پیگیری\u200cهای موجود"),
                            ("TASK", "وظایف موجود"),
                            ("TICKET", "تیکت\u200cهای موجود"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="موضوع تیکت",
                    ),
                ),
                (
                    "subject_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه موضوع"),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="برچسب\u200cها",
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="مهلت پاسخ"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ بستن"
                    ),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد پاسخ"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="آخرین پیام"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بسته\u200cشده توسط",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "followup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="followups.followup",
                        verbose_name="پیگیری مرتبط",
                    ),
                ),
                (
                    "last_message_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_ticket_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرستنده آخرین پیام",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="listings.listing",
                        verbose_name="آگهی مرتبط",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="properties.property",
                        verbose_name="ملک مرتبط",
                    ),
                ),
                (
                    "related_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_tickets",
                        to="tickets.ticket",
                        verbose_name="تیکت مرتبط",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tasks.task",
                        verbose_name="وظیفه مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت\u200cها",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "ایجاد تیکت"),
                            ("REPLIED", "ارسال پاسخ"),
                            ("READ", "مشاهده تیکت"),
                            ("CLOSED", "بستن تیکت"),
                            ("REOPENED", "بازگشایی تیکت"),
                            ("UPDATED", "ویرایش تیکت"),
                            ("RECIPIENT_ADDED", "افزودن گیرنده"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="جزئیات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر انجام\u200cدهنده",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="tickets.ticket",
                        verbose_name="تیکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه تیکت",
                "verbose_name_plural": "سوابق تیکت",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن پیام")),
                (
                    "is_initial",
                    models.BooleanField(default=False, verbose_name="پیام اولیه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرستنده",
                    ),
                ),
                (
                    "thread_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_thread_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده رشته خصوصی",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tickets.ticket",
                        verbose_name="تیکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام تیکت",
                "verbose_name_plural": "پیام\u200cهای تیکت",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.tickets.models.ticket_attachment_upload_to,
                        validators=[
                            apps.tickets.models.validate_ticket_file,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("pdf", "jpg", "jpeg", "png", "webp")
                            ),
                        ],
                        verbose_name="فایل",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="نام اصلی فایل"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع محتوا"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10485760)],
                        verbose_name="حجم",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بارگذاری"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticketmessage",
                        verbose_name="پیام",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست تیکت",
                "verbose_name_plural": "پیوست\u200cهای تیکت",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "ثبت\u200cکننده"), ("RECIPIENT", "گیرنده")],
                        max_length=12,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="خوانده شده"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ مشاهده"
                    ),
                ),
                (
                    "last_visible_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین پیام قابل مشاهده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
                (
                    "last_visible_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_visible_last_senders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرستنده آخرین پیام قابل مشاهده",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tickets.ticket",
                        verbose_name="تیکت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو تیکت",
                "verbose_name_plural": "اعضای تیکت",
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_by", "-created_at"], name="ticket_creator_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["subject_type", "subject_id"], name="ticket_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "-updated_at"], name="ticket_status_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority", "-updated_at"], name="ticket_priority_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("subject_type", "PROPERTY"),
                        ("property__isnull", False),
                        ("listing__isnull", True),
                        ("followup__isnull", True),
                        ("task__isnull", True),
                        ("related_ticket__isnull", True),
                    ),
                    models.Q(
                        ("subject_type", "LISTING"),
                        ("property__isnull", True),
                        ("listing__isnull", False),
                        ("followup__isnull", True),
                        ("task__isnull", True),
                        ("related_ticket__isnull", True),
                    ),
                    models.Q(
                        ("subject_type", "FOLLOWUP"),
                        ("property__isnull", True),
                        ("listing__isnull", True),
                        ("followup__isnull", False),
                        ("task__isnull", True),
                        ("related_ticket__isnull", True),
                    ),
                    models.Q(
                        ("subject_type", "TASK"),
                        ("property__isnull", True),
                        ("listing__isnull", True),
                        ("followup__isnull", True),
                        ("task__isnull", False),
                        ("related_ticket__isnull", True),
                    ),
                    models.Q(
                        ("subject_type", "TICKET"),
                        ("property__isnull", True),
                        ("listing__isnull", True),
                        ("followup__isnull", True),
                        ("task__isnull", True),
                        ("related_ticket__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ticket_exactly_one_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditevent",
            index=models.Index(
                fields=["ticket", "-created_at"], name="ticket_audit_ticket_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditevent",
            index=models.Index(
                fields=["actor", "-created_at"], name="ticket_audit_actor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketmessage",
            index=models.Index(
                fields=["ticket", "created_at"], name="ticket_msg_ticket_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketmessage",
            index=models.Index(
                fields=["ticket", "thread_recipient", "created_at"],
                name="ticket_msg_thread_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["message", "created_at"], name="ticket_attach_msg_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketparticipant",
            index=models.Index(
                fields=["user", "is_read"], name="ticket_part_user_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketparticipant",
            index=models.Index(
                fields=["ticket", "role"], name="ticket_part_ticket_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketparticipant",
            index=models.Index(
                fields=["user", "last_visible_sender"],
                name="ticket_part_user_sender_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketparticipant",
            constraint=models.UniqueConstraint(
                fields=("ticket", "user"), name="ticket_unique_participant"
            ),
        ),
    ]
