# Generated by Django 5.2.16 on 2026-08-23 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticketmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True)),
                fields=("ticket",),
                name="ticket_one_initial_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "OWNER")),
                fields=("ticket",),
                name="ticket_single_owner",
            ),
        ),
    ]
