# Generated by Django 5.2.16 on 2026-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_ticketmessage_ticket_one_initial_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="شماره تیکت",
            ),
        ),
    ]
