# Generated by Django 5.2.16 on 2026-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_alter_ticket_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketparticipant",
            name="visible_reply_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="تعداد پاسخ\u200cهای قابل مشاهده"
            ),
        ),
    ]
