# Generated by Django 5.2.16 on 2026-07-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'بروزرسانی'), ('delete', 'حذف'), ('archive', 'بایگانی'), ('complete', 'تکمیل'), ('status_change', 'تغییر وضعیت'), ('approve', 'تایید'), ('reject', 'رد'), ('export', 'خروجی')], db_index=True, max_length=20)),
                ('target_type', models.CharField(choices=[('property', 'ملک'), ('listing', 'آگهی'), ('task', 'وظیفه'), ('followup', 'پیگیری'), ('consultant', 'مشاور'), ('system', 'سیستم')], db_index=True, max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='common_acti_user_id_b871d5_idx'), models.Index(fields=['target_type', '-created_at'], name='common_acti_target__f4408e_idx'), models.Index(fields=['action', '-created_at'], name='common_acti_action_e166bf_idx')],
            },
        ),
    ]
