# Generated by Django 5.2.16 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('password_reset_request', 'درخواست تغییر رمز عبور'), ('password_changed', 'تغییر رمز عبور'), ('task_assigned', 'وظیفه جدید'), ('task_status_changed', 'تغییر وضعیت وظیفه'), ('followup_created', 'پیگیری جدید'), ('property_assigned', 'ملک جدید'), ('listing_approved', 'تایید آگهی'), ('listing_rejected', 'رد آگهی')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='common_noti_user_id_053883_idx'), models.Index(fields=['user', 'is_read'], name='common_noti_user_id_aae5b0_idx')],
            },
        ),
    ]
