# Generated by Django 5.2.16 on 2026-07-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ فعالیت', 'verbose_name_plural': 'لاگ\u200cهای فعالیت'},
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'تنظیمات شرکت', 'verbose_name_plural': 'تنظیمات شرکت'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'منطقه / محله', 'verbose_name_plural': 'مناطق و محله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'ایجاد'), ('update', 'بروزرسانی'), ('delete', 'حذف'), ('archive', 'بایگانی'), ('complete', 'تکمیل'), ('status_change', 'تغییر وضعیت'), ('approve', 'تایید'), ('reject', 'رد'), ('export', 'خروجی')], db_index=True, max_length=20, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.CharField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه هدف'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(choices=[('property', 'ملک'), ('listing', 'آگهی'), ('task', 'وظیفه'), ('followup', 'پیگیری'), ('consultant', 'مشاور'), ('system', 'سیستم')], db_index=True, max_length=20, verbose_name='نوع هدف'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره پروانه'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام منطقه / محله'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('password_reset_request', 'درخواست تغییر رمز عبور'), ('password_changed', 'تغییر رمز عبور'), ('task_assigned', 'وظیفه جدید'), ('task_status_changed', 'تغییر وضعیت وظیفه'), ('followup_created', 'پیگیری جدید'), ('property_assigned', 'ملک جدید'), ('listing_approved', 'تایید آگهی'), ('listing_rejected', 'رد آگهی')], max_length=50, verbose_name='نوع اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
