# Generated by Django 5.2.16 on 2026-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='ai_api_base_url',
            field=models.CharField(blank=True, help_text='مثلاً https://api.openai.com/v1 (سازگار با قالب OpenAI chat/completions)', max_length=500, verbose_name='آدرس پایه API هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='برای سرویس\u200cهای محلی/بدون احراز هویت می\u200cتواند خالی بماند.', max_length=500, verbose_name='کلید API هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='مثلاً gpt-4o-mini، deepseek-chat، gemini-1.5-flash و …', max_length=200, verbose_name='نام مدل'),
        ),
    ]
