# Generated by Django 5.2.16 on 2026-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_companysettings_ai_api_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='اختیاری است؛ اگر خالی بماند سرویس\u200cدهنده مدل پیش\u200cفرض خودش را استفاده می\u200cکند. مثلاً gpt-4o-mini، deepseek-chat، gemini-1.5-flash.', max_length=200, verbose_name='نام مدل (اختیاری)'),
        ),
    ]
