# Generated by Django 5.2.16 on 2026-07-28 08:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
        ('properties', '0005_alter_property_options_alter_propertyimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['scheduled_at', '-created_at'], 'verbose_name': 'پیگیری', 'verbose_name_plural': 'پیگیری\u200cها'},
        ),
        migrations.AlterField(
            model_name='followup',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بایگانی'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='followups', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مشاور'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='نام مشتری / مخاطب'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Meeting', 'Meeting'), ('Email', 'Email'), ('Site Visit', 'Site Visit')], default='Call', max_length=20, verbose_name='نوع پیگیری'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='outcome',
            field=models.TextField(blank=True, null=True, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='probability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Probability of closing from 0 to 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='احتمال موفقیت'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ملک'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان سررسید'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
