# Generated by Django 5.0.7 on 2026-08-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_alter_followup_options_alter_followup_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'پیگیری', 'verbose_name_plural': 'پیگیری\u200cها'},
        ),
    ]
