# Generated by Django 5.2.16 on 2026-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_alter_followup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('Call', 'تماس تلفنی'), ('Meeting', 'جلسه حضوری'), ('Email', 'ارسال پیام/ایمیل'), ('Site Visit', 'بازدید میدانی ملک')], default='Call', max_length=20, verbose_name='نوع پیگیری'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('completed', 'تکمیل\u200cشده')], default='scheduled', max_length=20, verbose_name='وضعیت'),
        ),
    ]
