# Generated by Django 5.2.16 on 2026-07-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_change_listing_default_to_active'),
        ('properties', '0005_alter_property_options_alter_propertyimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی\u200cها'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listings', to=settings.AUTH_USER_MODEL, verbose_name='مسئول آگهی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_listings', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='آگهی ویژه'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publish_channel',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram'), ('OTHER', 'Other')], max_length=30, verbose_name='کانال انتشار'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان آگهی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
