# Generated by Django 5.2.16 on 2026-07-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
        ('listings', '0003_alter_listing_options_alter_listing_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='basics.dealtype', verbose_name='نوع معامله'),
        ),
        migrations.CreateModel(
            name='ListingAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('value_integer', models.BigIntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='مقدار اعشاری')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='مقدار بله/خیر')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='مقدار تاریخ')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='مقدار چندتایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی آگهی',
                'verbose_name_plural': 'مقادیر ویژگی آگهی',
                'db_table': 'listings_listing_attribute_value',
                'indexes': [models.Index(fields=['attribute', 'value_integer'], name='idx_lav_attr_int'), models.Index(fields=['attribute', 'value_decimal'], name='idx_lav_attr_dec'), models.Index(fields=['attribute', 'value_boolean'], name='idx_lav_attr_bool'), models.Index(fields=['attribute', 'value_date'], name='idx_lav_attr_date')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'attribute'), name='uq_listing_attribute_value')],
            },
        ),
    ]
