# Generated by Django 5.2.16 on 2026-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_deal_type_listingattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deposit',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ رهن / ودیعه'),
        ),
        migrations.AddField(
            model_name='listing',
            name='monthly_rent',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=18, null=True, verbose_name='اجاره ماهانه'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات قیمت'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=18, null=True, verbose_name='قیمت فروش'),
        ),
    ]
