# Generated by Django 5.2.16 on 2026-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_deposit_listing_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20, verbose_name='وضعیت'),
        ),
    ]
