# Generated by Django 5.2.16 on 2026-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(choices=[(1, 'اولویت کم'), (2, 'اولویت عادی'), (3, 'اولویت بالا'), (4, 'اولویت فوری')], default=2, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publish_channel',
            field=models.CharField(choices=[('WEBSITE', 'وب\u200cسایت'), ('INSTAGRAM', 'اینستاگرام'), ('TELEGRAM', 'تلگرام'), ('OTHER', 'سایر')], max_length=30, verbose_name='کانال انتشار'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'منتشرشده (فعال)'), ('PAUSED', 'متوقف\u200cشده'), ('SOLD', 'فروخته\u200cشده'), ('EXPIRED', 'منقضی\u200cشده'), ('ARCHIVED', 'بایگانی\u200cشده')], default='ACTIVE', max_length=20, verbose_name='وضعیت'),
        ),
    ]
