# Generated by Django 5.2.16 on 2026-07-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_alter_propertyimage_options_and_more'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف'},
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Consultant assigned to this task', limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسئول انجام'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the task was marked completed', null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(help_text='Admin or consultant who created the task', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the task', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='When the task should be completed', verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property related to this task (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='properties.property', verbose_name='ملک مرتبط'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('VIEWING', 'Viewing'), ('DOCUMENT', 'Document'), ('NEGOTIATION', 'Negotiation'), ('FOLLOW_UP', 'Follow-Up'), ('ADMINISTRATIVE', 'Administrative'), ('SITE_VISIT', 'Site Visit'), ('CONTRACT', 'Contract'), ('INSPECTION', 'Inspection')], default='VIEWING', max_length=20, verbose_name='نوع وظیفه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Brief title of the task', max_length=255, verbose_name='عنوان وظیفه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
