# Generated by Django 5.2.16 on 2026-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'اولویت کم'), ('MEDIUM', 'اولویت عادی'), ('HIGH', 'اولویت بالا'), ('URGENT', 'اولویت فوری')], default='MEDIUM', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار انجام'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تکمیل\u200cشده'), ('CANCELLED', 'لغوشده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('VIEWING', 'بازدید ملک'), ('DOCUMENT', 'بررسی مدارک'), ('NEGOTIATION', 'مذاکره و نشست'), ('FOLLOW_UP', 'پیگیری مستمر'), ('ADMINISTRATIVE', 'امور اداری و دفتری'), ('SITE_VISIT', 'کارشناسی میدانی'), ('CONTRACT', 'عقد قرارداد'), ('INSPECTION', 'بازرسی فنی')], default='VIEWING', max_length=20, verbose_name='نوع وظیفه'),
        ),
    ]
