# Generated by Django 4.2.4 on 2026-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('STUDIO', 'Studio'), ('PENTHOUSE', 'Penthouse'), ('COMMERCIAL', 'Commercial'), ('OFFICE', 'Office'), ('SHOP', 'Shop'), ('LAND', 'Land'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
