# Generated by Django 5.2.16 on 2026-07-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصاویر ملک'},
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='مشاور مسئول'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=20, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='internal_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد داخلی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(max_length=255, verbose_name='محله / منطقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('STUDIO', 'Studio'), ('PENTHOUSE', 'Penthouse'), ('COMMERCIAL', 'Commercial'), ('OFFICE', 'Office'), ('SHOP', 'Shop'), ('LAND', 'Land'), ('OTHER', 'Other')], max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد خواب'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('INACTIVE', 'Archived')], default='AVAILABLE', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
