# Generated by Django 5.2.16 on 2026-07-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
        ('properties', '0005_alter_property_options_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='basics.propertytype', verbose_name='نوع ملک'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='basics.propertyusage', verbose_name='کاربری ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('STUDIO', 'Studio'), ('PENTHOUSE', 'Penthouse'), ('COMMERCIAL', 'Commercial'), ('OFFICE', 'Office'), ('SHOP', 'Shop'), ('LAND', 'Land'), ('OTHER', 'Other')], max_length=20, verbose_name='نوع ملک (قدیمی)'),
        ),
        migrations.CreateModel(
            name='PropertyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('value_integer', models.BigIntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='مقدار اعشاری')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='مقدار بله/خیر')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='مقدار تاریخ')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='مقدار چندتایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.attribute', verbose_name='ویژگی')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='properties.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی ملک',
                'verbose_name_plural': 'مقادیر ویژگی ملک',
                'db_table': 'properties_property_attribute_value',
                'indexes': [models.Index(fields=['attribute', 'value_integer'], name='idx_pav_attr_int'), models.Index(fields=['attribute', 'value_decimal'], name='idx_pav_attr_dec'), models.Index(fields=['attribute', 'value_boolean'], name='idx_pav_attr_bool'), models.Index(fields=['attribute', 'value_date'], name='idx_pav_attr_date')],
                'constraints': [models.UniqueConstraint(fields=('property', 'attribute'), name='uq_property_attribute_value')],
            },
        ),
    ]
