# Generated by Django 5.2.16 on 2026-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_property_type_ref_property_property_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='قیمت (منسوخ — در آگهی ثبت می\u200cشود)'),
        ),
    ]
