# Generated by Django 5.2.16 on 2026-07-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_province_city_district_and_more'),
        ('properties', '0007_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='basics.district', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='محله / منطقه (متنی)'),
        ),
    ]
