# Generated by Django 5.2.16 on 2026-08-14 12:20

import apps.properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/', validators=[apps.properties.validators.validate_property_image], verbose_name='تصویر'),
        ),
    ]
