# Generated by Django 5.2.16 on 2026-08-21 13:29

from django.db import migrations, transaction


def _generate_for_existing(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    props = list(Property.objects.all().order_by("id"))

    # Find max existing sequential code
    max_val = 1110
    import re
    for prop in props:
        code = prop.internal_code or ""
        match = re.match(r"^ZF_(\d+)$", code)
        if match:
            digits = match.group(1)
            if "0" not in digits:
                try:
                    val = int(digits)
                    if val > max_val:
                        max_val = val
                except ValueError:
                    pass

    # Rewrite all existing properties in order
    for prop in props:
        max_val += 1
        while "0" in str(max_val):
            max_val += 1
        digits = f"{max_val:04d}" if max_val <= 9999 else f"{max_val:05d}"
        prop.internal_code = f"ZF_{digits}"
        prop.save(update_fields=["internal_code"])


def reverse_rewrite(apps, schema_editor):
    # Reverse is a no-op; original codes are lost intentionally per spec.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_propertyimage_image"),
    ]

    operations = [
        migrations.RunPython(_generate_for_existing, reverse_rewrite),
    ]
