# Generated by Django 5.2.16 on 2026-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20260821_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام مالک'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام خانوادگی مالک'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره موبایل مالک'),
        ),
    ]
