# Generated by Django 5.2.16 on 2026-08-23 18:44

import apps.properties.models
import apps.properties.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_backfill_owner_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAppraisalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فقط فایل PDF، حداکثر ۱۰ مگابایت.', upload_to=apps.properties.models.appraisal_report_upload_path, validators=[apps.properties.validators.validate_appraisal_pdf], verbose_name='فایل گزارش کارشناسی')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام اصلی فایل')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم فایل (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_report', to='properties.property', verbose_name='ملک')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_appraisal_reports', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری\u200cکننده')),
            ],
            options={
                'verbose_name': 'گزارش کارشناسی ملک',
                'verbose_name_plural': 'گزارش\u200cهای کارشناسی ملک',
            },
        ),
    ]
