# Generated by Django 5.2.16 on 2026-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertyappraisalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('SALE', 'فروش'), ('RENT', 'اجاره')], max_length=20, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'آپارتمان'), ('VILLA', 'ویلا'), ('TOWNHOUSE', 'خانه ویلایی'), ('STUDIO', 'استودیو'), ('PENTHOUSE', 'پنت\u200cهاوس'), ('COMMERCIAL', 'تجاری/اداری'), ('OFFICE', 'دفتر کار'), ('SHOP', 'مغازه'), ('LAND', 'زمین'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع ملک (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'آماده واگذاری'), ('RESERVED', 'رزرو شده'), ('SOLD', 'فروخته/واگذارشده'), ('INACTIVE', 'بایگانی\u200cشده')], default='AVAILABLE', max_length=20, verbose_name='وضعیت'),
        ),
    ]
