# Generated by Django 5.2.16 on 2026-09-05 14:25

import apps.properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_add_list_filter_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(db_index=True, upload_to='properties/images/', validators=[apps.properties.validators.validate_property_image], verbose_name='تصویر'),
        ),
    ]
