# Generated by Django 5.2.16 on 2026-07-26 15:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_consultantprofile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian mobile number.', regex='^09\\d{9}$')])),
                ('branch', models.CharField(blank=True, default='شعبه مرکزی', max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admins/profile/')),
                ('hired_at', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['full_name'],
            },
        ),
    ]
