# Generated by Django 5.2.16 on 2026-07-28 08:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='branch',
            field=models.CharField(blank=True, default='شعبه مرکزی', max_length=255, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='hired_at',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست. شماره باید با ۰۹ شروع شود و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admins/profile/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='branch',
            field=models.CharField(max_length=255, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='hired_at',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست. شماره باید با ۰۹ شروع شود و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultants/profile/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تلاش ناموفق'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='last_user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='مرورگر'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='قفل تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent')], db_index=True, default='AGENT', max_length=20, verbose_name='نقش کاربری'),
        ),
    ]
